id: IE79C9AE3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:24:55+00:00'
last_modified: '2022-06-08T08:40:10.416413+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26078
  title: གེ་སར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    53A2:
      image_group_id: I4390
      title: ''
      total_pages: 714
      order: 1
      base_file: 53A2.txt
    C49F:
      image_group_id: I4391
      title: ''
      total_pages: 464
      order: 2
      base_file: C49F.txt
    '5801':
      image_group_id: I4392
      title: ''
      total_pages: 478
      order: 3
      base_file: 5801.txt
    8E76:
      image_group_id: I4393
      title: ''
      total_pages: 454
      order: 4
      base_file: 8E76.txt
    CB4A:
      image_group_id: I4394
      title: ''
      total_pages: 396
      order: 5
      base_file: CB4A.txt
    8D83:
      image_group_id: I4395
      title: ''
      total_pages: 546
      order: 6
      base_file: 8D83.txt
    040C:
      image_group_id: I4396
      title: ''
      total_pages: 762
      order: 7
      base_file: 040C.txt
    061F:
      image_group_id: I4397
      title: ''
      total_pages: 560
      order: 8
      base_file: 061F.txt
    72D2:
      image_group_id: I4398
      title: ''
      total_pages: 550
      order: 9
      base_file: 72D2.txt
    '7748':
      image_group_id: I4399
      title: ''
      total_pages: 404
      order: 10
      base_file: 7748.txt
    BDDA:
      image_group_id: I4400
      title: ''
      total_pages: 352
      order: 11
      base_file: BDDA.txt
    ACD8:
      image_group_id: I4401
      title: ''
      total_pages: 350
      order: 12
      base_file: ACD8.txt
    A10C:
      image_group_id: I4402
      title: ''
      total_pages: 484
      order: 13
      base_file: A10C.txt
    03D3:
      image_group_id: I4403
      title: ''
      total_pages: 686
      order: 14
      base_file: 03D3.txt
    1E2A:
      image_group_id: I4404
      title: ''
      total_pages: 446
      order: 15
      base_file: 1E2A.txt
    BA22:
      image_group_id: I4405
      title: ''
      total_pages: 708
      order: 16
      base_file: BA22.txt
    4A69:
      image_group_id: I4406
      title: ''
      total_pages: 302
      order: 17
      base_file: 4A69.txt
    '4058':
      image_group_id: I4407
      title: ''
      total_pages: 392
      order: 18
      base_file: 4058.txt
    74D9:
      image_group_id: I4408
      title: ''
      total_pages: 604
      order: 19
      base_file: 74D9.txt
    21A5:
      image_group_id: I4409
      title: ''
      total_pages: 600
      order: 20
      base_file: 21A5.txt
    F7F8:
      image_group_id: I4410
      title: ''
      total_pages: 488
      order: 21
      base_file: F7F8.txt
    '8387':
      image_group_id: I4411
      title: ''
      total_pages: 398
      order: 22
      base_file: 8387.txt
    01F8:
      image_group_id: I4412
      title: ''
      total_pages: 348
      order: 23
      base_file: 01F8.txt
    E448:
      image_group_id: I4413
      title: ''
      total_pages: 278
      order: 24
      base_file: E448.txt
    67C4:
      image_group_id: I4414
      title: ''
      total_pages: 426
      order: 25
      base_file: 67C4.txt
    49D1:
      image_group_id: I4415
      title: ''
      total_pages: 602
      order: 26
      base_file: 49D1.txt
    B55D:
      image_group_id: I4416
      title: ''
      total_pages: 394
      order: 27
      base_file: B55D.txt
    B1A4:
      image_group_id: I4417
      title: ''
      total_pages: 336
      order: 28
      base_file: B1A4.txt
    CDDD:
      image_group_id: I4418
      title: ''
      total_pages: 530
      order: 29
      base_file: CDDD.txt
    AA9B:
      image_group_id: I4419
      title: ''
      total_pages: 680
      order: 30
      base_file: AA9B.txt
    7DA1:
      image_group_id: I4420
      title: ''
      total_pages: 362
      order: 31
      base_file: 7DA1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
