id: P009107
initial_creation_type: ocr
source_metadata:
  id: bdr:W26078
  title: གེ་སར
  author: ''
  volumes:
    ac75f524d9924b81aab3d6480e499599:
      image_group_id: I4390
      title: ''
      volume_number: 1
      total_pages: 714
      base_file: v001.txt
    c202278233bd4702b12ca4eaed6f62f9:
      image_group_id: I4391
      title: ''
      volume_number: 2
      total_pages: 464
      base_file: v002.txt
    79c40b1ddf8e4f8f84307c84105351b0:
      image_group_id: I4392
      title: ''
      volume_number: 3
      total_pages: 478
      base_file: v003.txt
    604f90aadf994450b4c3cc872046b0bb:
      image_group_id: I4393
      title: ''
      volume_number: 4
      total_pages: 454
      base_file: v004.txt
    5b4365c2895f455ea2806f43662a7265:
      image_group_id: I4394
      title: ''
      volume_number: 5
      total_pages: 396
      base_file: v005.txt
    1e1be76f977249c299566642e22ad2b9:
      image_group_id: I4395
      title: ''
      volume_number: 6
      total_pages: 546
      base_file: v006.txt
    df868f64360f4e9c91028f66ff8174a7:
      image_group_id: I4396
      title: ''
      volume_number: 7
      total_pages: 762
      base_file: v007.txt
    71a87e13f40944e889d6fb2fe222c730:
      image_group_id: I4397
      title: ''
      volume_number: 8
      total_pages: 560
      base_file: v008.txt
    8887d5c43e404d1ba94788f6b0c82dc5:
      image_group_id: I4398
      title: ''
      volume_number: 9
      total_pages: 550
      base_file: v009.txt
    c705d31cb04646b9bbdfe387e26d555a:
      image_group_id: I4399
      title: ''
      volume_number: 10
      total_pages: 404
      base_file: v010.txt
    a5a8e95e42964096a7f2b1d2e9f86b9c:
      image_group_id: I4400
      title: ''
      volume_number: 11
      total_pages: 352
      base_file: v011.txt
    f313388dd66242b394949329cebc269f:
      image_group_id: I4401
      title: ''
      volume_number: 12
      total_pages: 350
      base_file: v012.txt
    e10b4266b0384817b18d3d427a6a81db:
      image_group_id: I4402
      title: ''
      volume_number: 13
      total_pages: 484
      base_file: v013.txt
    21d0566f29af413aa8c30cdaf4cbe937:
      image_group_id: I4403
      title: ''
      volume_number: 14
      total_pages: 686
      base_file: v014.txt
    e6d459e14df54d5b87b699990e258f51:
      image_group_id: I4404
      title: ''
      volume_number: 15
      total_pages: 446
      base_file: v015.txt
    72596c095114456caf39d0f95207a0de:
      image_group_id: I4405
      title: ''
      volume_number: 16
      total_pages: 708
      base_file: v016.txt
    a72e96a8b9b9402eb988ab5a366cb6d6:
      image_group_id: I4406
      title: ''
      volume_number: 17
      total_pages: 302
      base_file: v017.txt
    81d5b23673934714b14ebb45aecb53c0:
      image_group_id: I4407
      title: ''
      volume_number: 18
      total_pages: 392
      base_file: v018.txt
    54bb8d6bea2242968f28f158fea9f641:
      image_group_id: I4408
      title: ''
      volume_number: 19
      total_pages: 604
      base_file: v019.txt
    2406f112729d4b4bac45fa38d2325d5e:
      image_group_id: I4409
      title: ''
      volume_number: 20
      total_pages: 600
      base_file: v020.txt
    c4a3332e3ba84f68a3b00fd844712d35:
      image_group_id: I4410
      title: ''
      volume_number: 21
      total_pages: 488
      base_file: v021.txt
    bc85480e9e4b4e73afd23221fdcb298f:
      image_group_id: I4411
      title: ''
      volume_number: 22
      total_pages: 398
      base_file: v022.txt
    8650626cbeb6491186e5fe04bc8e0112:
      image_group_id: I4412
      title: ''
      volume_number: 23
      total_pages: 348
      base_file: v023.txt
    4e18f13bba8440fab54f808d88c754f8:
      image_group_id: I4413
      title: ''
      volume_number: 24
      total_pages: 278
      base_file: v024.txt
    80e9d2bc3b5d4bf3ab42f2707080b925:
      image_group_id: I4414
      title: ''
      volume_number: 25
      total_pages: 426
      base_file: v025.txt
    60a5d1d2105d4930b1a09b1e4a21cb2d:
      image_group_id: I4415
      title: ''
      volume_number: 26
      total_pages: 602
      base_file: v026.txt
    7b0d5e028ef342a396802ebb48c7f51b:
      image_group_id: I4416
      title: ''
      volume_number: 27
      total_pages: 394
      base_file: v027.txt
    ba5de08b64804ade810a092dadea838f:
      image_group_id: I4417
      title: ''
      volume_number: 28
      total_pages: 336
      base_file: v028.txt
    735a524ad92a4aef8e5a193335ea16f4:
      image_group_id: I4418
      title: ''
      volume_number: 29
      total_pages: 530
      base_file: v029.txt
    39445688c9a9469e81607c85781ea6c6:
      image_group_id: I4419
      title: ''
      volume_number: 30
      total_pages: 680
      base_file: v030.txt
    d34f58a43dcb43fabaf1004917358476:
      image_group_id: I4420
      title: ''
      volume_number: 31
      total_pages: 362
      base_file: v031.txt
